# basic
algorithm: "HER-DQN"
env_id: "GoalGridworld-v0"

# seed
seed: 1

# cuda
gpu_id: 0

# replay buffer
replay_buffer_kwargs:
  max_size: 100000
  fraction_goals_rollout_goals: 0.2
  fraction_goals_env_goals: 0.0

# training
algorithm_kwargs:
  num_epochs: 100
  num_eval_steps_per_epoch: 1000
  num_trains_per_train_loop: 1000
  num_expl_steps_per_train_loop: 1000
  min_num_steps_before_training: 1000
  max_path_length: 50
  batch_size: 128

trainer_kwargs:
  discount: 0.99