# env
env_id: "empty-maze-v0"

# seed
seed: 1 #4076 #1

# cuda
gpu_id: 0

# log
log_to_wandb: false #true

# training dataset
dataset_name: "empty-maze-v0-triplet.pkl"

# model
hidden_dim: 512
hidden_layer: 2
output_dim: 2

# train
loss_type: "triplet"
batch_size: 512   # batch size per update
learning_rate: 5e-4 #1e-3  # learning rate for ADAM optimizer
max_train_epochs: 50 

# log
log_every_batches: 1000